tasks:
  - init: ./gradlew build
image:
  file: .gitpod.Dockerfile
vscode:
  extensions:
    - contextmapper.context-mapper-vscode-extension@5.12.1:Qyp9s4+yIylFMaNPx2FPtQ==
    - jebbs.plantuml@2.13.12:LcphKtCbPTIScvq6ELiS8Q==